project_id = "uogkklwfvwoxkifpkzpu"

[functions.send-email]
verify_jwt = false

[functions.notify-order-status]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.notify-expiring-points]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = false

[functions.kelpay-payment]
verify_jwt = false

[functions.kelpay-callback]
verify_jwt = false

[functions.kelpay-check]
verify_jwt = false

[functions.calculate-shipping]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.push-notifications]
verify_jwt = false

[functions.visual-search]
verify_jwt = false

[functions.impersonate-user]
verify_jwt = false

[functions.ai-user-analysis]
verify_jwt = false

[functions.expire-pending-orders]
verify_jwt = false

[functions.verify-confirmation-code]
verify_jwt = false
